### ISSUE TITLE
Help Armenia!

### ISSUE THREAD

**Issue by mikayelgr** [pnpm/.github#1]
![Armenian Flag](https://user-images.githubusercontent.com/56165400/193562321-6a5b150a-2a94-4a11-9fcc-efd830830233.png)

### Please do not ignore this! Stand by the people of [Armenia](https://en.wikipedia.org/wiki/Armenia)!

It's been more than 2 weeks, since Azerbaijan carried out a wide-scale attack against targets in Armenia, an unprecedented escalation of the long-running conflict on to Armenian territory. They continue to accuse us of being the aggressor, similar to the case with Ukraine and Russia. 

### Azerbaijan is **killing** our soldiers, **invading** our territories, and **raping** women!

> Armenia’s defense ministry reported attacks, starting around midnight September 13, targeting cities all along the southern part of Armenia’s border with Azerbaijan, including Vardenis, Sotk, Artanish, Ishkhanasar, Goris and Kapan.
 

> Azerbaijan’s defense ministry [said](https://mod.gov.az/en/news/information-of-the-ministry-of-defense-of-the-republic-of-azerbaijan-42337.html) it was merely carrying out “local countermeasures” in response to “the large-scale provocation” from Armenia: “News about the invasion of Azerbaijan into the territory of Armenia, disseminated in the Armenian media and the segment of social networks, is nothing but nonsense.”
 

> While Azerbaijan has regularly used military escalation in its conflict with Armenia to achieve diplomatic results, in the past the fighting has been limited almost exclusively to the area in and around Nagorno-Karabakh, internationally recognized as Azerbaijani territory. The expansion into Armenia represents another level of escalation. What remains unclear is whether this is another attempt to achieve diplomatic gains or is the precursor to more military action.

Source: https://eurasianet.org/azerbaijan-launches-wide-ranging-attacks-against-armenia

### BBC: Armenia says 105 troops killed in Azerbaijan border clashes
> https://www.bbc.com/news/world-europe-62828239 (Sep. 15)

### France24: Armenia, Azerbaijan trade blame over armed border clashes
> https://www.france24.com/en/asia-pacific/20220914-armenia-accuses-azerbaijan-of-launching-renewed-attacks-on-border (Sep. 14)

**Comment by zkochan** [comment]
I understand the problems of Armenia but currently we only put banners for Ukraine because I live in Ukraine and Russia's aggression directly affects my life.
